version: '3'

services:
  postgres:
    image: postgres
    container_name: be-movie
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
